#!/bin/bash

set -x

TMPDIR=$(mktemp -d)

boot docs \
  && scp -r target/api-docs/ "$TMPDIR" \
  && git checkout gh-pages \
  && rm -rf target/ \
  && scp -r "$TMPDIR/" . \
  && rm -rf "$TMPDIR" \
  && git add --all \
  && git commit -m "Update API documentation" \
  && git push origin gh-pages \
  && git checkout master
